"""verified field add

Revision ID: 395ea39c5b24
Revises: 5e9d54a979c6
Create Date: 2026-02-22 13:40:59.218971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '395ea39c5b24'
down_revision: Union[str, Sequence[str], None] = '5e9d54a979c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign', 'is_verified')
    # ### end Alembic commands ###
