"""table filed name changed

Revision ID: 5e9d54a979c6
Revises: b95607b54df9
Create Date: 2026-02-18 18:03:30.471930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e9d54a979c6'
down_revision: Union[str, Sequence[str], None] = 'b95607b54df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_id'), 'verification', ['id'], unique=False)
    op.create_table('account',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=511), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=511), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.add_column('HOSPITAL', sa.Column('hospital_tel2', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_callback_tel', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_fax', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_email', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_city', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_zip', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_sms_count', sa.Integer(), nullable=True))
    op.add_column('HOSPITAL', sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=True))
    op.add_column('HOSPITAL', sa.Column('recent_login', sa.DateTime(), nullable=True))
    op.add_column('HOSPITAL', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('HOSPITAL', sa.Column('hospital_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_sign_sign_email'), 'sign', ['sign_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_sign_email'), table_name='sign')
    op.drop_column('HOSPITAL', 'hospital_deleted')
    op.drop_column('HOSPITAL', 'updated_by')
    op.drop_column('HOSPITAL', 'created_by')
    op.drop_column('HOSPITAL', 'recent_login')
    op.drop_column('HOSPITAL', 'memo')
    op.drop_column('HOSPITAL', 'hospital_sms_count')
    op.drop_column('HOSPITAL', 'hospital_zip')
    op.drop_column('HOSPITAL', 'hospital_region')
    op.drop_column('HOSPITAL', 'hospital_city')
    op.drop_column('HOSPITAL', 'hospital_email')
    op.drop_column('HOSPITAL', 'hospital_fax')
    op.drop_column('HOSPITAL', 'hospital_callback_tel')
    op.drop_column('HOSPITAL', 'hospital_tel2')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_verification_id'), table_name='verification')
    op.drop_table('verification')
    # ### end Alembic commands ###
