"""sign role field add

Revision ID: 795f5c37994b
Revises: b99c6086ba2d
Create Date: 2026-02-17 12:45:20.781188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '795f5c37994b'
down_revision: Union[str, Sequence[str], None] = 'b99c6086ba2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign', sa.Column('sign_role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign', 'sign_role')
    # ### end Alembic commands ###
