"""user table add

Revision ID: b95607b54df9
Revises: 795f5c37994b
Create Date: 2026-02-18 16:55:56.389730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b95607b54df9'
down_revision: Union[str, Sequence[str], None] = '795f5c37994b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HOSPITAL',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('hospital_master', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('hospital_tel1', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('hospital_address1', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True),
    sa.Column('hospital_address2', sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_index(op.f('ix_HOSPITAL_hospital_id'), 'HOSPITAL', ['hospital_id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('sign',
    sa.Column('sign_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('sign_email', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sign_cellphone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sign_license_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sign_department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sign_jobtitle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sign_id', sa.Integer(), nullable=False),
    sa.Column('sign_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sign_role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['HOSPITAL.hospital_id'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('sign_id'),
    sa.UniqueConstraint('sign_cellphone')
    )
    op.create_index(op.f('ix_sign_sign_id'), 'sign', ['sign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_sign_id'), table_name='sign')
    op.drop_table('sign')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_HOSPITAL_hospital_id'), table_name='HOSPITAL')
    op.drop_table('HOSPITAL')
    # ### end Alembic commands ###
