"""Foreinkey change

Revision ID: b99c6086ba2d
Revises: fa336f72c564
Create Date: 2026-02-13 21:52:55.297768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b99c6086ba2d'
down_revision: Union[str, Sequence[str], None] = 'fa336f72c564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.add_column('HOSPITAL', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('HOSPITAL', 'created_at')
    op.drop_constraint(op.f('sign_ibfk_1'), 'sign', type_='foreignkey')
    op.create_foreign_key(None, 'sign', 'HOSPITAL', ['hospital_id'], ['hospital_id'], onupdate='CASCADE', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sign', type_='foreignkey')
    op.create_foreign_key(op.f('sign_ibfk_1'), 'sign', 'HOSPITAL', ['hospital_id'], ['hospital_id'])
    op.add_column('HOSPITAL', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.drop_column('HOSPITAL', 'create_at')
    op.create_table('user',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###
